// jscript/vue/sample-blog/src/components/PageSite.vue
<template>
    <div v-if="page">
        <Page v-bind:page="page" />
    </div>
    <div v-else-if="page === null">
        Page not found
    </div>
    <div v-else>
        Loading page...
    </div>
</template>

<script>
import { getPage } from './../service';
import Page from './Page.vue'

export default {
    name: 'PostsSite',
    components: {
        Page
    },
    data: () => {
        return {
            page: null
        }
    },
    methods: {
        loadPage: async function(slug) {
            this.page = undefined;

            try {
                const result = await getPage(slug);

                this.page = result;
            } catch (ex) {
                this.page = null;
            }
        }
    },
    created: function() {
        this.loadPage(this.$route.params.slug)
    },
    watch: {
        $route: {
            handler: function(to) {
                this.loadPage(to.params.slug);
            }
        }
    }
}
</script>

// jscript/react/sample-hotels/src/components/PageSite.js
import React from 'react';
import { useParams } from 'react-router-dom';
import { Page } from './Page.js';
import { getPage } from './../service';

export const PageSite = () => {
    const { slug } = useParams();

    const [page, setPage] = React.useState(undefined);

    React.useEffect(() => {
        setPage(undefined);

        async function fetchData() {
            try {
                const result = await getPage(slug);
        
                setPage(result);
            } catch (ex) {
                setPage(null);
            }
        }

        fetchData();
    }, [slug]);

    if (page) {
        return <Page page={page} />
    } else if (page === null) {
        return <div>Page not found.</div>
    } else {
        return <div>Loading Page...</div>
    }
}
