// jscript/vue/sample-blog/src/components/PostSite.vue
<template>
    <div v-if="post">
        <Post v-bind:post="post" />
    </div>
    <div v-else-if="post === null">
        Post not found
    </div>
    <div v-else>
        Loading post...
    </div>
</template>

<script>
import { getPost } from './../service';
import Post from './Post.vue'

export default {
    name: 'PostsSite',
    components: {
        Post
    },
    data: () => {
        return {
            post: null
        }
    },
    methods: {
        loadPost: async function(id) {
            this.post = undefined;

            try {
                const result = await getPost(id);

                this.post = result;
            } catch (ex) {
                this.post = null;
            }
        }
    },
    created: function() {
        this.loadPost(this.$route.params.id)
    },
    watch: {
        $route: {
            handler: function(to) {
                this.loadPost(to.params.id);
            }
        }
    }
}
</script>

// jscript/react/sample-hotels/src/components/PostSite.jsx
import React from 'react';
import { useParams } from 'react-router-dom';
import { Post } from './Post';
import { getPost, getPostsIds } from '../service';
import { useRefresh } from './hooks';

export const PostSite = () => {
    const { id } = useParams();

    const [post, setPost] = React.useState(undefined);
    const needsUpdate = useRefresh(getPostsIds([post.id]));

    React.useEffect(() => {
        async function fetchData() {
            try {
                const result = await getPost(id);
        
                setPost(result);
            } catch (ex) {
                setPost(null);
            }
        }

        fetchData();
    }, [id, needsUpdate]);

    if (post) {
        return <Post post={post} />
    } else if (post === null) {
        return <div>Post not found.</div>
    } else {
        return <div>Loading Post...</div>
    }
}
