// jscript/react/sample-hotels/src/components/PostsSite.jsx
import React from 'react';
import { Post } from './Post';
import { getPosts, getPostsIds } from '../service';
import { useRefresh } from './hooks';

export const PostsSite = () => {
    const [posts, setPosts] = React.useState();
    const needsUpdate = useRefresh(getPostsIds(posts));

    React.useEffect(() => {
        async function fetchData() {
            const results = await getPosts();
    
            setPosts(results.items);
        }

        fetchData();
    }, [needsUpdate]);

    if (!posts) {
        return <div>Loading Posts...</div>
    }

    return (
        <>
            {posts.length === 0 ? (
                <>No Post found</>
            ) : (
                <div>
                    {posts.map(post => (
                        <div key={post.id}>
                            <Post key={post.id} post={post} withLink={true} />

                            <hr />
                        </div>
                    ))}
                </div>
            )}
        </>
    );
}

// jscript/vue/sample-blog/src/components/PostsSite.vue
<template>
    <div v-if="posts">
        <div v-for="post in posts" v-bind:key="post.id">
            <Post v-bind:post="post" v-bind:withLink="true" />

            <hr />
        </div>
    </div>
    <div v-else>
        Loading posts...
    </div>
</template>

<script>
import { getPosts } from './../service';
import Post from './Post.vue'

export default {
    name: 'PostsSite',
    components: {
        Post
    },
    data: () => {
        return {
            posts: null
        }
    },
    methods: {
        loadPosts: async function() {
            this.posts = null;

            try {
                const result = await getPosts();

                this.posts = result.posts;
            } catch (ex) {
                this.posts = [];
            }

        }
    },
    created: function() {
        this.loadPosts();
    }
}
</script>
