// jscript/react/sample-hotels/src/components/Post.js
import React from 'react';
import { Link } from 'react-router-dom';
import { Markdown } from './Markdown';

export const Post = ({ post, withLink }) => {
    const { id, flatData: data } = post;

    return (
        <div>
            {withLink ? (
                <Link to={`/blog/${id}/${data.slug}`}>
                    <h2>{data.title}</h2>
                </Link>
            ) : (
                <h2>{data.title}</h2>
            )}

            <Markdown markdown={data.text.text} references={data.text.contents} />
        </div>
    );
};

// jscript/vue/sample-blog/src/components/Post.vue
<template>
    <div>
        <div v-if="withLink">
            <router-link :to="{ name: 'blog', params: { slug: post.slug, id: post.id }}">
                <h2>{{post.title}}</h2>
            </router-link>
        </div>
        <div v-else>
            <h2>{{post.title}}</h2>
        </div>

        <div v-html="post.text"></div>
    </div>
</template>

<script>
export default {
    name: 'Post',
    props: {
        post: Object,
        withLink: Boolean
    }
}
</script>
