// jscript/vue/sample-blog/src/components/Post.vue
<template>
    <div>
        <div v-if="withLink">
            <router-link :to="{ name: 'blog', params: { slug: post.slug, id: post.id }}">
                <h2>{{post.title}}</h2>
            </router-link>
        </div>
        <div v-else>
            <h2>{{post.title}}</h2>
        </div>

        <div v-html="post.text"></div>
    </div>
</template>

<script>
export default {
    name: 'Post',
    props: {
        post: Object,
        withLink: Boolean
    }
}
</script>

// jscript/react/sample-compose/src/shared/Post.tsx
import { Link } from 'react-router-dom';
import { flatten } from '../utils';
import { Markdown } from './Markdown';

export const Post = ({ post, withLink }: { post: any, withLink?: true }) => {
    const { id } = post;
    const postData = flatten(post);

    return (
        <div>
            {withLink ? (
                <Link to={`/blog/${id}/${postData.slug}`}>
                    <h2>{postData.title}</h2>
                </Link>
            ) : (
                <h2>{postData.title}</h2>
            )}

            <Markdown markdown={postData.text.text} references={postData.text.contents} />
        </div>
    );
};
