// jscript/angular/sample-blog/src/app/top-nav/top-nav.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ContentService, Page } from '../services/content.service';

@Component({
    selector: 'app-top-nav',
    templateUrl: './top-nav.component.html',
    styleUrls: ['./top-nav.component.scss']
})
export class TopNavComponent implements OnInit {
    public pages$: Observable<Page[]>;

    constructor(
        public readonly contentsService: ContentService
    ) {
    }

    public ngOnInit() {
        this.pages$ = this.contentsService.getPages().pipe(
            map(x => x.pages)
        );
    }
}

<ng-container *ngIf="pages$ | async; let pages">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item" *ngFor="let page of pages">
            <a [routerLink]="['/pages', page.slug]" routerLinkActive="active" class="nav-link">{{page.title}}</a>
        </li>
    </ul>
</ng-container>

// jscript/react/sample-blog/src/components/TopNav.js
import React from 'react';
import { NavLink } from 'react-router-dom';
import { getPages } from './../service';

export const TopNav = () => {
    const [pages, setPages] = React.useState([]);

    React.useEffect(() => {
        async function fetchData() {
            const results = await getPages();
    
            setPages(results.pages);
        }

        fetchData();
    }, []);

    return (
        <ul className='navbar-nav mr-auto'>
            {pages.map(page => (
                <li key={page.id} className='nav-item'>
                    <NavLink activeClassName='active' className='nav-link' to={`/pages/${page.slug}`}>{page.title}</NavLink>
                </li>
            ))}
        </ul>
    )
};
