// jscript/vue/sample-blog/src/components/TopNav.vue
<template>
    <ul class="navbar-nav mr-auto">
        <li v-for="page in pages" v-bind:key="page.id" class="nav-item">
            <a activeClassName="active" class="nav-link">{{page.title}}</a>
        </li>
    </ul>
</template>

<script>
import { getPages } from "./../service";

export default {
    name: "TopNav",
    data: () => {
        return {
            pages: null
        }
    },
    created: function() {
        const component = this;

        async function loadPages() {
            try {
                const result = await getPages();

                component.pages = result.pages;
            } catch (ex) {
                component.pages = [];
            }
        }

        loadPages();
    }
}
</script>

// jscript/react/sample-blog/src/components/TopNav.js
import React from 'react';
import { NavLink } from 'react-router-dom';
import { getPages } from './../service';

export const TopNav = () => {
    const [pages, setPages] = React.useState([]);

    React.useEffect(() => {
        async function fetchData() {
            const results = await getPages();
    
            setPages(results.pages);
        }

        fetchData();
    }, []);

    return (
        <ul className='navbar-nav mr-auto'>
            {pages.map(page => (
                <li key={page.id} className='nav-item'>
                    <NavLink activeClassName='active' className='nav-link' to={`/pages/${page.slug}`}>{page.title}</NavLink>
                </li>
            ))}
        </ul>
    )
};
